import Head from 'next/head'
import Navigation from '../components/Navigation'
import Carts from './carts'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tshirt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Carts />
        <Navigation />
        {/*React.Children.toArray(props.children)*/}
      </div>
    </>
  )
}
